In [1]:
import numpy as np
import pandas as pd
import numpy as np
import pandas as pd
import sys
import csv
import functools
from functools import reduce
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime
import re
import string
import statistics

import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
#from sklearn import svm
#from sklearn.svm import SVC
from sklearn.model_selection import KFold 
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [2]:
df = pd.read_pickle("./3_COMB_File_CLEANED_1.pkl")
udf = pd.read_pickle("./3_COMB_FILE_UNDERSAMPLING")
odf2 = pd.read_pickle("./3_COMB_FILE_OVERSAMPLINGx2")
odf3 = pd.read_pickle("./3_COMB_FILE_OVERSAMPLINGx3")
odf4 = pd.read_pickle("./3_COMB_FILE_OVERSAMPLINGx4")
odf5 = pd.read_pickle("./3_COMB_FILE_OVERSAMPLINGx5")
odfsame = pd.read_pickle("./3_COMB_FILE_OVERSAMPLINGsame")

In [3]:
# create bag of words for df
cv = CountVectorizer(stop_words='english')
data_cv = cv.fit_transform(df.CLEAN_FOI_TEXT)
df_dtm = pd.DataFrame(data_cv.toarray(), columns=cv.get_feature_names())
df_dtm.index = df.index
print(df_dtm.shape)

# train-test split for df
X_df = df_dtm
y_df = df["RECALL_CLASS"]

X_df_train, X_df_test, y_df_train, y_df_test = train_test_split(X_df, y_df, test_size = 0.33, random_state = 0)
print(X_df_train.shape)
print(X_df_test.shape)
print(y_df_train.shape)
print(y_df_test.shape)

(42208, 7424)
(28279, 7424)
(13929, 7424)
(28279,)
(13929,)


In [4]:
# create bag of words for udf
cv_u = CountVectorizer(stop_words='english')
data_cv_u = cv_u.fit_transform(udf.CLEAN_FOI_TEXT)
udf_dtm = pd.DataFrame(data_cv_u.toarray(), columns=cv_u.get_feature_names())
udf_dtm.index = udf.index
print(udf_dtm.shape)

# train-test split for udf
X_u = udf_dtm
y_u = udf["RECALL_CLASS"]

X_u_train, X_u_test, y_u_train, y_u_test = train_test_split(X_u, y_u, test_size = 0.33, random_state = 0)
print(X_u_train.shape)
print(X_u_test.shape)
print(y_u_train.shape)
print(y_u_test.shape)

(11292, 4313)
(7565, 4313)
(3727, 4313)
(7565,)
(3727,)


In [5]:
# create bag of words for odf2
cv_o2 = CountVectorizer(stop_words='english')
data_cv_o2 = cv_o2.fit_transform(odf2.CLEAN_FOI_TEXT)
odf2_dtm = pd.DataFrame(data_cv_o2.toarray(), columns=cv_o2.get_feature_names())
odf2_dtm.index = odf2.index
print(odf2_dtm.shape)

# train-test split for odf2
X_o2 = odf2_dtm
y_o2 = odf2["RECALL_CLASS"]

X_o2_train, X_o2_test, y_o2_train, y_o2_test = train_test_split(X_o2, y_o2, test_size = 0.33, random_state = 0)
print(X_o2_train.shape)
print(X_o2_test.shape)
print(y_o2_train.shape)
print(y_o2_test.shape)

(51692, 7424)
(34633, 7424)
(17059, 7424)
(34633,)
(17059,)


In [6]:
# create bag of words for odf3
cv_o3 = CountVectorizer(stop_words='english')
data_cv_o3 = cv_o3.fit_transform(odf3.CLEAN_FOI_TEXT)
odf3_dtm = pd.DataFrame(data_cv_o3.toarray(), columns=cv_o3.get_feature_names())
odf3_dtm.index = odf3.index
print(odf3_dtm.shape)

# train-test split for odf3
X_o3 = odf3_dtm
y_o3 = odf3["RECALL_CLASS"]

X_o3_train, X_o3_test, y_o3_train, y_o3_test = train_test_split(X_o3, y_o3, test_size = 0.33, random_state = 0)
print(X_o3_train.shape)
print(X_o3_test.shape)
print(y_o3_train.shape)
print(y_o3_test.shape)

(61176, 7424)
(40987, 7424)
(20189, 7424)
(40987,)
(20189,)


In [7]:
# create bag of words for odf4
cv_o4 = CountVectorizer(stop_words='english')
data_cv_o4 = cv_o4.fit_transform(odf4.CLEAN_FOI_TEXT)
odf4_dtm = pd.DataFrame(data_cv_o4.toarray(), columns=cv_o4.get_feature_names())
odf4_dtm.index = odf4.index
print(odf4_dtm.shape)

# train-test split for odf4
X_o4 = odf4_dtm
y_o4 = odf4["RECALL_CLASS"]

X_o4_train, X_o4_test, y_o4_train, y_o4_test = train_test_split(X_o4, y_o4, test_size = 0.33, random_state = 0)
print(X_o4_train.shape)
print(X_o4_test.shape)
print(y_o4_train.shape)
print(y_o4_test.shape)

(70660, 7424)
(47342, 7424)
(23318, 7424)
(47342,)
(23318,)


In [8]:
# create bag of words for odf5
cv_o5 = CountVectorizer(stop_words='english')
data_cv_o5 = cv_o5.fit_transform(odf5.CLEAN_FOI_TEXT)
odf5_dtm = pd.DataFrame(data_cv_o5.toarray(), columns=cv_o5.get_feature_names())
odf5_dtm.index = odf5.index
print(odf5_dtm.shape)

# train-test split for odf5
X_o5 = odf5_dtm
y_o5 = odf5["RECALL_CLASS"]

X_o5_train, X_o5_test, y_o5_train, y_o5_test = train_test_split(X_o5, y_o5, test_size = 0.33, random_state = 0)
print(X_o5_train.shape)
print(X_o5_test.shape)
print(y_o5_train.shape)
print(y_o5_test.shape)

(80144, 7424)
(53696, 7424)
(26448, 7424)
(53696,)
(26448,)


In [9]:
# create bag of words for odfsame
cv_osame = CountVectorizer(stop_words='english')
data_cv_osame = cv_osame.fit_transform(odfsame.CLEAN_FOI_TEXT)
odfsame_dtm = pd.DataFrame(data_cv_osame.toarray(), columns=cv_osame.get_feature_names())
odfsame_dtm.index = odfsame.index
print(odfsame_dtm.shape)

# train-test split for odfsame
X_osame = odfsame_dtm
y_osame = odfsame["RECALL_CLASS"]

X_osame_train, X_osame_test, y_osame_train, y_osame_test = train_test_split(X_osame, y_osame, test_size = 0.33, random_state = 0)
print(X_osame_train.shape)
print(X_osame_test.shape)
print(y_osame_train.shape)
print(y_osame_test.shape)

(98172, 7424)
(65775, 7424)
(32397, 7424)
(65775,)
(32397,)


In [10]:
# running naive-bayes classifiers

In [11]:
'''
classifierdf = GaussianNB()
cvScore_df = cross_val_score(classifierdf, X_df_train, y_df_train, cv=10)
print(cvScore_df)
print(statistics.mean(cvScore_df))
'''

'\nclassifierdf = GaussianNB()\ncvScore_df = cross_val_score(classifierdf, X_df_train, y_df_train, cv=10)\nprint(cvScore_df)\nprint(statistics.mean(cvScore_df))\n'

In [12]:
# for unbalanced class data
classifierdf = GaussianNB()
classifierdf.fit(X_df_train, y_df_train)
ydfPredNB = classifierdf.predict(X_df_test)
print("Unbalanced classes")
print(confusion_matrix(y_df_test,ydfPredNB))
print('\n')
print(classification_report(y_df_test,ydfPredNB))

Unbalanced classes
[[3170 6115 1570]
 [ 149 1593  171]
 [ 119  449  593]]


              precision    recall  f1-score   support

           0       0.92      0.29      0.44     10855
           1       0.20      0.83      0.32      1913
           2       0.25      0.51      0.34      1161

    accuracy                           0.38     13929
   macro avg       0.46      0.55      0.37     13929
weighted avg       0.77      0.38      0.42     13929



In [13]:
# for undersampled class data
classifieru = GaussianNB()
classifieru.fit(X_u_train, y_u_train)
yuPredNB = classifieru.predict(X_u_test)
print("Undersampled classes")
print(confusion_matrix(y_u_test,yuPredNB))
print('\n')
print(classification_report(y_u_test,yuPredNB))

Undersampled classes
[[ 497  576  125]
 [  56 1111   92]
 [  62  724  484]]


              precision    recall  f1-score   support

           0       0.81      0.41      0.55      1198
           1       0.46      0.88      0.61      1259
           2       0.69      0.38      0.49      1270

    accuracy                           0.56      3727
   macro avg       0.65      0.56      0.55      3727
weighted avg       0.65      0.56      0.55      3727



In [14]:
# for oversampled (x2) class data
classifier = GaussianNB()
classifier.fit(X_o2_train, y_o2_train)
yo2PredNB = classifier.predict(X_o2_test)
print("Oversampled (x2) classes")
print(confusion_matrix(y_o2_test,yo2PredNB))
print('\n')
print(classification_report(y_o2_test,yo2PredNB))

Oversampled (x2) classes
[[2490 2839 5441]
 [  56 1258 2494]
 [  80   29 2372]]


              precision    recall  f1-score   support

           0       0.95      0.23      0.37     10770
           1       0.30      0.33      0.32      3808
           2       0.23      0.96      0.37      2481

    accuracy                           0.36     17059
   macro avg       0.49      0.51      0.35     17059
weighted avg       0.70      0.36      0.36     17059



In [15]:
# for oversampled (x3) class data
classifier = GaussianNB()
classifier.fit(X_o3_train, y_o3_train)
yo3PredNB = classifier.predict(X_o3_test)
print("Oversampled (x3) classes")
print(confusion_matrix(y_o3_test,yo3PredNB))
print('\n')
print(classification_report(y_o3_test,yo3PredNB))

Oversampled (x3) classes
[[2460 2969 5341]
 [  33 1854 3823]
 [  39   64 3606]]


              precision    recall  f1-score   support

           0       0.97      0.23      0.37     10770
           1       0.38      0.32      0.35      5710
           2       0.28      0.97      0.44      3709

    accuracy                           0.39     20189
   macro avg       0.54      0.51      0.39     20189
weighted avg       0.68      0.39      0.38     20189



In [16]:
# for oversampled (x4) class data
classifier = GaussianNB()
classifier.fit(X_o4_train, y_o4_train)
yo4PredNB = classifier.predict(X_o4_test)
print("Oversampled (x4) classes")
print(confusion_matrix(y_o4_test,yo4PredNB))
print('\n')
print(classification_report(y_o4_test,yo4PredNB))

Oversampled (x4) classes
[[2355 2841 5454]
 [  20 2673 4933]
 [   8   59 4975]]


              precision    recall  f1-score   support

           0       0.99      0.22      0.36     10650
           1       0.48      0.35      0.41      7626
           2       0.32      0.99      0.49      5042

    accuracy                           0.43     23318
   macro avg       0.60      0.52      0.42     23318
weighted avg       0.68      0.43      0.40     23318



In [17]:
# for oversampled (x5) class data
classifier = GaussianNB()
classifier.fit(X_o5_train, y_o5_train)
yo5PredNB = classifier.predict(X_o5_test)
print("Oversampled (x5) classes")
print(confusion_matrix(y_o5_test,yo5PredNB))
print('\n')
print(classification_report(y_o5_test,yo5PredNB))

Oversampled (x5) classes
[[2408 1832 6348]
 [   5 3276 6298]
 [  10   70 6201]]


              precision    recall  f1-score   support

           0       0.99      0.23      0.37     10588
           1       0.63      0.34      0.44      9579
           2       0.33      0.99      0.49      6281

    accuracy                           0.45     26448
   macro avg       0.65      0.52      0.44     26448
weighted avg       0.71      0.45      0.43     26448



In [18]:
# for oversampled (same) class data
classifier = GaussianNB()
classifier.fit(X_osame_train, y_osame_train)
yosamePredNB = classifier.predict(X_osame_test)
print("Oversampled (xsame) classes")
print(confusion_matrix(y_osame_test,yosamePredNB))
print('\n')
print(classification_report(y_osame_test,yosamePredNB))

Oversampled (xsame) classes
[[ 2375  2927  5481]
 [    6  3864  6928]
 [    0    79 10737]]


              precision    recall  f1-score   support

           0       1.00      0.22      0.36     10783
           1       0.56      0.36      0.44     10798
           2       0.46      0.99      0.63     10816

    accuracy                           0.52     32397
   macro avg       0.67      0.52      0.48     32397
weighted avg       0.67      0.52      0.48     32397



In [19]:
# running descision tree classifiers

In [20]:
# for unbalanced class data
classifierdf = DecisionTreeClassifier()
classifierdf.fit(X_df_train, y_df_train)
ydfPredNB = classifierdf.predict(X_df_test)
print("Unbalanced classes")
print(confusion_matrix(y_df_test,ydfPredNB))
print('\n')
print(classification_report(y_df_test,ydfPredNB))

Unbalanced classes
[[9706  787  362]
 [ 893  955   65]
 [ 374   64  723]]


              precision    recall  f1-score   support

           0       0.88      0.89      0.89     10855
           1       0.53      0.50      0.51      1913
           2       0.63      0.62      0.63      1161

    accuracy                           0.82     13929
   macro avg       0.68      0.67      0.68     13929
weighted avg       0.81      0.82      0.82     13929



In [21]:
# for undersampled class data
classifieru = GaussianNB()
classifieru.fit(X_u_train, y_u_train)
yuPredNB = classifieru.predict(X_u_test)
print("Undersampled classes")
print(confusion_matrix(y_u_test,yuPredNB))
print('\n')
print(classification_report(y_u_test,yuPredNB))

Undersampled classes
[[ 497  576  125]
 [  56 1111   92]
 [  62  724  484]]


              precision    recall  f1-score   support

           0       0.81      0.41      0.55      1198
           1       0.46      0.88      0.61      1259
           2       0.69      0.38      0.49      1270

    accuracy                           0.56      3727
   macro avg       0.65      0.56      0.55      3727
weighted avg       0.65      0.56      0.55      3727



In [22]:
# for oversampled (x2) class data
classifier = DecisionTreeClassifier()
classifier.fit(X_o2_train, y_o2_train)
yo2PredNB = classifier.predict(X_o2_test)
print("Oversampled (x2) classes")
print(confusion_matrix(y_o2_test,yo2PredNB))
print('\n')
print(classification_report(y_o2_test,yo2PredNB))

Oversampled (x2) classes
[[9319  978  473]
 [ 557 3185   66]
 [ 280   63 2138]]


              precision    recall  f1-score   support

           0       0.92      0.87      0.89     10770
           1       0.75      0.84      0.79      3808
           2       0.80      0.86      0.83      2481

    accuracy                           0.86     17059
   macro avg       0.82      0.85      0.84     17059
weighted avg       0.86      0.86      0.86     17059



In [23]:
# for oversampled (x3) class data
classifier = DecisionTreeClassifier()
classifier.fit(X_o3_train, y_o3_train)
yo3PredNB = classifier.predict(X_o3_test)
print("Oversampled (x3) classes")
print(confusion_matrix(y_o3_test,yo3PredNB))
print('\n')
print(classification_report(y_o3_test,yo3PredNB))

Oversampled (x3) classes
[[9161 1097  512]
 [ 309 5356   45]
 [  99   43 3567]]


              precision    recall  f1-score   support

           0       0.96      0.85      0.90     10770
           1       0.82      0.94      0.88      5710
           2       0.86      0.96      0.91      3709

    accuracy                           0.90     20189
   macro avg       0.88      0.92      0.90     20189
weighted avg       0.90      0.90      0.90     20189



In [24]:
# for oversampled (x4) class data
classifier = DecisionTreeClassifier()
classifier.fit(X_o4_train, y_o4_train)
yo4PredNB = classifier.predict(X_o4_test)
print("Oversampled (x4) classes")
print(confusion_matrix(y_o4_test,yo4PredNB))
print('\n')
print(classification_report(y_o4_test,yo4PredNB))

Oversampled (x4) classes
[[8954 1133  563]
 [ 200 7397   29]
 [  84   26 4932]]


              precision    recall  f1-score   support

           0       0.97      0.84      0.90     10650
           1       0.86      0.97      0.91      7626
           2       0.89      0.98      0.93      5042

    accuracy                           0.91     23318
   macro avg       0.91      0.93      0.92     23318
weighted avg       0.92      0.91      0.91     23318



In [25]:
# for oversampled (x5) class data
classifier = DecisionTreeClassifier()
classifier.fit(X_o5_train, y_o5_train)
yo5PredNB = classifier.predict(X_o5_test)
print("Oversampled (x5) classes")
print(confusion_matrix(y_o5_test,yo5PredNB))
print('\n')
print(classification_report(y_o5_test,yo5PredNB))

Oversampled (x5) classes
[[8901 1136  551]
 [  99 9463   17]
 [  81   34 6166]]


              precision    recall  f1-score   support

           0       0.98      0.84      0.91     10588
           1       0.89      0.99      0.94      9579
           2       0.92      0.98      0.95      6281

    accuracy                           0.93     26448
   macro avg       0.93      0.94      0.93     26448
weighted avg       0.93      0.93      0.93     26448



In [26]:
# for oversampled (same) class data
classifier = DecisionTreeClassifier()
classifier.fit(X_osame_train, y_osame_train)
yosamePredNB = classifier.predict(X_osame_test)
print("Oversampled (xsame) classes")
print(confusion_matrix(y_osame_test,yosamePredNB))
print('\n')
print(classification_report(y_osame_test,yosamePredNB))

Oversampled (xsame) classes
[[ 9003  1165   615]
 [   86 10684    28]
 [   30    13 10773]]


              precision    recall  f1-score   support

           0       0.99      0.83      0.90     10783
           1       0.90      0.99      0.94     10798
           2       0.94      1.00      0.97     10816

    accuracy                           0.94     32397
   macro avg       0.94      0.94      0.94     32397
weighted avg       0.94      0.94      0.94     32397



In [27]:
# running KNN classifiers

In [28]:
# for unbalanced class data
classifierdf = KNeighborsClassifier(n_neighbors=1)
classifierdf.fit(X_df_train, y_df_train)
ydfPredNB = classifierdf.predict(X_df_test)
print("Unbalanced classes")
print(confusion_matrix(y_df_test,ydfPredNB))
print('\n')
print(classification_report(y_df_test,ydfPredNB))

Unbalanced classes
[[9703  805  347]
 [ 837  986   90]
 [ 404   67  690]]


              precision    recall  f1-score   support

           0       0.89      0.89      0.89     10855
           1       0.53      0.52      0.52      1913
           2       0.61      0.59      0.60      1161

    accuracy                           0.82     13929
   macro avg       0.68      0.67      0.67     13929
weighted avg       0.81      0.82      0.82     13929



In [29]:
# for undersampled class data
classifieru = KNeighborsClassifier(n_neighbors=1)
classifieru.fit(X_u_train, y_u_train)
yuPredNB = classifieru.predict(X_u_test)
print("Undersampled classes")
print(confusion_matrix(y_u_test,yuPredNB))
print('\n')
print(classification_report(y_u_test,yuPredNB))

Undersampled classes
[[848 221 129]
 [223 933 103]
 [174 110 986]]


              precision    recall  f1-score   support

           0       0.68      0.71      0.69      1198
           1       0.74      0.74      0.74      1259
           2       0.81      0.78      0.79      1270

    accuracy                           0.74      3727
   macro avg       0.74      0.74      0.74      3727
weighted avg       0.74      0.74      0.74      3727



In [30]:
# for oversampled (x2) class data
classifier = KNeighborsClassifier(n_neighbors=1)
classifier.fit(X_o2_train, y_o2_train)
yo2PredNB = classifier.predict(X_o2_test)
print("Oversampled (x2) classes")
print(confusion_matrix(y_o2_test,yo2PredNB))
print('\n')
print(classification_report(y_o2_test,yo2PredNB))

Oversampled (x2) classes
[[9326 1009  435]
 [ 505 3227   76]
 [ 292   42 2147]]


              precision    recall  f1-score   support

           0       0.92      0.87      0.89     10770
           1       0.75      0.85      0.80      3808
           2       0.81      0.87      0.84      2481

    accuracy                           0.86     17059
   macro avg       0.83      0.86      0.84     17059
weighted avg       0.87      0.86      0.86     17059



In [31]:
# for oversampled (x3) class data
classifier = KNeighborsClassifier(n_neighbors=1)
classifier.fit(X_o3_train, y_o3_train)
yo3PredNB = classifier.predict(X_o3_test)
print("Oversampled (x3) classes")
print(confusion_matrix(y_o3_test,yo3PredNB))
print('\n')
print(classification_report(y_o3_test,yo3PredNB))

Oversampled (x3) classes
[[9201 1123  446]
 [ 341 5338   31]
 [ 132   37 3540]]


              precision    recall  f1-score   support

           0       0.95      0.85      0.90     10770
           1       0.82      0.93      0.87      5710
           2       0.88      0.95      0.92      3709

    accuracy                           0.90     20189
   macro avg       0.88      0.91      0.90     20189
weighted avg       0.90      0.90      0.90     20189



In [32]:
# for oversampled (x4) class data
classifier = KNeighborsClassifier(n_neighbors=1)
classifier.fit(X_o4_train, y_o4_train)
yo4PredNB = classifier.predict(X_o4_test)
print("Oversampled (x4) classes")
print(confusion_matrix(y_o4_test,yo4PredNB))
print('\n')
print(classification_report(y_o4_test,yo4PredNB))

Oversampled (x4) classes
[[8947 1195  508]
 [ 218 7365   43]
 [  73   26 4943]]


              precision    recall  f1-score   support

           0       0.97      0.84      0.90     10650
           1       0.86      0.97      0.91      7626
           2       0.90      0.98      0.94      5042

    accuracy                           0.91     23318
   macro avg       0.91      0.93      0.92     23318
weighted avg       0.92      0.91      0.91     23318



In [33]:
# for oversampled (x5) class data
classifier = KNeighborsClassifier(n_neighbors=1)
classifier.fit(X_o5_train, y_o5_train)
yo5PredNB = classifier.predict(X_o5_test)
print("Oversampled (x5) classes")
print(confusion_matrix(y_o5_test,yo5PredNB))
print('\n')
print(classification_report(y_o5_test,yo5PredNB))

Oversampled (x5) classes
[[8930 1166  492]
 [ 174 9392   13]
 [  91   41 6149]]


              precision    recall  f1-score   support

           0       0.97      0.84      0.90     10588
           1       0.89      0.98      0.93      9579
           2       0.92      0.98      0.95      6281

    accuracy                           0.93     26448
   macro avg       0.93      0.93      0.93     26448
weighted avg       0.93      0.93      0.92     26448



In [34]:
# for oversampled (same) class data
classifier = KNeighborsClassifier(n_neighbors=1)
classifier.fit(X_osame_train, y_osame_train)
yosamePredNB = classifier.predict(X_osame_test)
print("Oversampled (xsame) classes")
print(confusion_matrix(y_osame_test,yosamePredNB))
print('\n')
print(classification_report(y_osame_test,yosamePredNB))

Oversampled (xsame) classes
[[ 8961  1246   576]
 [  155 10624    19]
 [   35    29 10752]]


              precision    recall  f1-score   support

           0       0.98      0.83      0.90     10783
           1       0.89      0.98      0.94     10798
           2       0.95      0.99      0.97     10816

    accuracy                           0.94     32397
   macro avg       0.94      0.94      0.94     32397
weighted avg       0.94      0.94      0.94     32397



In [35]:
# running random forest classifier

In [36]:
# for unbalanced class data
classifierdf = RandomForestClassifier(n_estimators=100)
classifierdf.fit(X_df_train, y_df_train)
ydfPredNB = classifierdf.predict(X_df_test)
print("Unbalanced classes")
print(confusion_matrix(y_df_test,ydfPredNB))
print('\n')
print(classification_report(y_df_test,ydfPredNB))

Unbalanced classes
[[10434   304   117]
 [ 1080   804    29]
 [  495    19   647]]


              precision    recall  f1-score   support

           0       0.87      0.96      0.91     10855
           1       0.71      0.42      0.53      1913
           2       0.82      0.56      0.66      1161

    accuracy                           0.85     13929
   macro avg       0.80      0.65      0.70     13929
weighted avg       0.84      0.85      0.84     13929



In [37]:
# for undersampled class data
classifieru = RandomForestClassifier(n_estimators=100)
classifieru.fit(X_u_train, y_u_train)
yuPredNB = classifieru.predict(X_u_test)
print("Undersampled classes")
print(confusion_matrix(y_u_test,yuPredNB))
print('\n')
print(classification_report(y_u_test,yuPredNB))

Undersampled classes
[[ 854  209  135]
 [ 101 1058  100]
 [  59   69 1142]]


              precision    recall  f1-score   support

           0       0.84      0.71      0.77      1198
           1       0.79      0.84      0.82      1259
           2       0.83      0.90      0.86      1270

    accuracy                           0.82      3727
   macro avg       0.82      0.82      0.82      3727
weighted avg       0.82      0.82      0.82      3727



In [38]:
# for oversampled (x2) class data
classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(X_o2_train, y_o2_train)
yo2PredNB = classifier.predict(X_o2_test)
print("Oversampled (x2) classes")
print(confusion_matrix(y_o2_test,yo2PredNB))
print('\n')
print(classification_report(y_o2_test,yo2PredNB))

Oversampled (x2) classes
[[9997  581  192]
 [ 550 3226   32]
 [ 318   17 2146]]


              precision    recall  f1-score   support

           0       0.92      0.93      0.92     10770
           1       0.84      0.85      0.85      3808
           2       0.91      0.86      0.88      2481

    accuracy                           0.90     17059
   macro avg       0.89      0.88      0.88     17059
weighted avg       0.90      0.90      0.90     17059



In [39]:
# for oversampled (x3) class data
classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(X_o3_train, y_o3_train)
yo3PredNB = classifier.predict(X_o3_test)
print("Oversampled (x3) classes")
print(confusion_matrix(y_o3_test,yo3PredNB))
print('\n')
print(classification_report(y_o3_test,yo3PredNB))

Oversampled (x3) classes
[[9722  766  282]
 [ 311 5374   25]
 [ 116   25 3568]]


              precision    recall  f1-score   support

           0       0.96      0.90      0.93     10770
           1       0.87      0.94      0.91      5710
           2       0.92      0.96      0.94      3709

    accuracy                           0.92     20189
   macro avg       0.92      0.94      0.93     20189
weighted avg       0.93      0.92      0.92     20189



In [40]:
# for oversampled (x4) class data
classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(X_o4_train, y_o4_train)
yo4PredNB = classifier.predict(X_o4_test)
print("Oversampled (x4) classes")
print(confusion_matrix(y_o4_test,yo4PredNB))
print('\n')
print(classification_report(y_o4_test,yo4PredNB))

Oversampled (x4) classes
[[9495  809  346]
 [ 196 7398   32]
 [  58   21 4963]]


              precision    recall  f1-score   support

           0       0.97      0.89      0.93     10650
           1       0.90      0.97      0.93      7626
           2       0.93      0.98      0.96      5042

    accuracy                           0.94     23318
   macro avg       0.93      0.95      0.94     23318
weighted avg       0.94      0.94      0.94     23318



In [41]:
# for oversampled (x5) class data
classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(X_o5_train, y_o5_train)
yo5PredNB = classifier.predict(X_o5_test)
print("Oversampled (x5) classes")
print(confusion_matrix(y_o5_test,yo5PredNB))
print('\n')
print(classification_report(y_o5_test,yo5PredNB))

Oversampled (x5) classes
[[9386  880  322]
 [  63 9500   16]
 [  84   28 6169]]


              precision    recall  f1-score   support

           0       0.98      0.89      0.93     10588
           1       0.91      0.99      0.95      9579
           2       0.95      0.98      0.96      6281

    accuracy                           0.95     26448
   macro avg       0.95      0.95      0.95     26448
weighted avg       0.95      0.95      0.95     26448



In [42]:
# for oversampled (same) class data
classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(X_osame_train, y_osame_train)
yosamePredNB = classifier.predict(X_osame_test)
print("Oversampled (xsame) classes")
print(confusion_matrix(y_osame_test,yosamePredNB))
print('\n')
print(classification_report(y_osame_test,yosamePredNB))

Oversampled (xsame) classes
[[ 9507   895   381]
 [   64 10700    34]
 [   25    10 10781]]


              precision    recall  f1-score   support

           0       0.99      0.88      0.93     10783
           1       0.92      0.99      0.96     10798
           2       0.96      1.00      0.98     10816

    accuracy                           0.96     32397
   macro avg       0.96      0.96      0.96     32397
weighted avg       0.96      0.96      0.96     32397



In [52]:
dfNB_randfor["PRED"] = pd.DataFrame(yosamePredNB)
dfNB_randfor.index = y_osame_test.index
dfNB_randfor["IND"] = y_osame_test.index
dfNB_randfor.head()

0 PRED    IND
9915   0    0   9915
31774  2    2  31774
8748   1    1   8748
2325   1    1   2325
3215   2    2   3215

In [53]:
odfsame["IND2"] = odfsame.index
dfNB_randforM = dfNB_randfor.merge(odfsame, left_on="IND", right_on="IND2")
dfNB_randforM.head()

0 PRED    IND MDR_REPORT_KEY MDR_TEXT_KEY TEXT_TYPE_CODE  \
0  0    0   9915        1411042      1268339              D   
1  0    0   9915        1955154      1783281              D   
2  0    0   9915        1718127      1630396              D   
3  2    2  31774        2775649      3069072              D   
4  2    2  31774        1376996     21368292              D   

  PATIENT_SEQUENCE_NUMBER DATE_REPORT  \
0                       1         NaN   
1                       1         NaN   
2                       1         NaN   
3                       1         NaN   
4                       1         NaN   

                                            FOI_TEXT  textLen  ...  \
0       IT WAS REPORTED THAT THE LEAD WAS DISLODGED.      NaN  ...   
1  IT WAS REPORTED THAT THE LEAD WAS EXPLANTED DU...      NaN  ...   
2  IT WAS REPORTED THAT DURING THE IMPLANT PROCED...      NaN  ...   
3  BOSTON SCIENTIFIC RECEIVED INFORMATION THAT TH...      NaN  ...   
4  THE LEAD WAS EXPLANTED DUE TO NOISE OBSERVED O...      NaN  ...   

  DEVICE_EVALUATED_BY_MANUFACTUR  year   STD_MANUFACTURER  \
0                              Y  2009           ST. JUDE   
1                              R  2011           ST. JUDE   
2                              Y  2010          MEDTRONIC   
3                              R  2012  BOSTON SCIENTIFIC   
4                              R  2009           ST. JUDE   

                        STD_DEVICE RECALL_CLASS Before2013   CENSORED _merge  \
0                    STJUDE_DURATA            0       True 2009-07-09   both   
1                  STJUDE_RIATA_ST            1       True 2011-01-10   both   
2  MEDTRONIC_SPRINT_QUATTRO_SECURE            2       True 2010-06-10   both   
3        BOS_SCI_ENDOTAK_ENDURANCE            0       True 2012-10-08   both   
4                     STJUDE_RIATA            1       True 2009-05-09   both   

                                      CLEAN_FOI_TEXT   IND2  
0                         it report the lead dislodg   9915  
1             it report the lead explant due dislodg   9915  
2  it report dure implant procedur helix would ex...   9915  
3  mfgid receiv inform thi chloric rv lead di dev...  31774  
4           the lead explant due nois observ the egm  31774  

[5 rows x 46 columns]

In [74]:
dfNB_randforM2 = pd.DataFrame(dfNB_randforM[dfNB_randforM["PRED"] == "1"]['STD_DEVICE'].value_counts())
dfNB_randforM2.rename({"STD_DEVICE":"RECALL1"}, axis=1, inplace=True)
dfNB_randforM2["RECALL2"] = pd.DataFrame(dfNB_randforM[dfNB_randforM["PRED"] == "2"]['STD_DEVICE'].value_counts())
dfNB_randforM2["TOTAL"] = pd.DataFrame(dfNB_randforM['STD_DEVICE'].value_counts())
dfNB_randforM2["RECALLTOTAL"] = pd.DataFrame(dfNB_randforM2["RECALL2"]+dfNB_randforM2["RECALL1"])
dfNB_randforM2["RECALLPERCENTAGE"] = pd.DataFrame(dfNB_randforM2["RECALLTOTAL"]/dfNB_randforM2["TOTAL"])
dfNB_randforM2[dfNB_randforM2["TOTAL"] > 500].sort_values(by="RECALLPERCENTAGE")

RECALL1  RECALL2  TOTAL  RECALLTOTAL  \
BIOTRONIK_LUMAX                      231    227.0    808        458.0   
STJUDE_QUICKFLEX                     199    211.0    711        410.0   
BOS_SCI_ENDOTAK_RELIANCE            2266   2266.0   7780       4532.0   
BIOTRONIK_LINOX                      359    393.0   1260        752.0   
BOS_SCI_ENDOTAK_ENDURANCE            218    237.0    750        455.0   
MEDTRONIC_SPRINT_QUATTRO             667    788.0   2286       1455.0   
BOS_SCI_ENDOTAK_DSP                  233    221.0    689        454.0   
STJUDE_DURATA                       1979   1397.0   5037       3376.0   
MEDTRONIC_SPRINT                     637    762.0   2033       1399.0   
MEDTRONIC_TRANSVENE                  366    467.0   1186        833.0   
STJUDE_RIATA_ST                     2346   2125.0   5904       4471.0   
STJUDE_RIATA                        7115   6566.0  17994      13681.0   
MEDTRONIC_SPRINT_QUATTRO_SECURE     9937  10128.0  26333      20065.0   
SORIN_ISOLINE                        975   1008.0   2563       1983.0   
MEDTRONIC_SPRINT_FIDELIS            1948   1924.0   4985       3872.0   
STJUDE_RIATA_ST_OPTIM                388    236.0    798        624.0   

                                 RECALLPERCENTAGE  
BIOTRONIK_LUMAX                          0.566832  
STJUDE_QUICKFLEX                         0.576653  
BOS_SCI_ENDOTAK_RELIANCE                 0.582519  
BIOTRONIK_LINOX                          0.596825  
BOS_SCI_ENDOTAK_ENDURANCE                0.606667  
MEDTRONIC_SPRINT_QUATTRO                 0.636483  
BOS_SCI_ENDOTAK_DSP                      0.658926  
STJUDE_DURATA                            0.670240  
MEDTRONIC_SPRINT                         0.688146  
MEDTRONIC_TRANSVENE                      0.702361  
STJUDE_RIATA_ST                          0.757283  
STJUDE_RIATA                             0.760309  
MEDTRONIC_SPRINT_QUATTRO_SECURE          0.761972  
SORIN_ISOLINE                            0.773703  
MEDTRONIC_SPRINT_FIDELIS                 0.776730  
STJUDE_RIATA_ST_OPTIM                    0.781955

RECALL1  RECALL2  TOTAL  RECALLTOTAL  \
MEDTRONIC_SPRINT_QUATTRO_SECURE     9937  10128.0  26333      20065.0   
STJUDE_RIATA                        7115   6566.0  17994      13681.0   
STJUDE_RIATA_ST                     2346   2125.0   5904       4471.0   
BOS_SCI_ENDOTAK_RELIANCE            2266   2266.0   7780       4532.0   
STJUDE_DURATA                       1979   1397.0   5037       3376.0   

                                 RECALLPERCENTAGE  
MEDTRONIC_SPRINT_QUATTRO_SECURE          0.761972  
STJUDE_RIATA                             0.760309  
STJUDE_RIATA_ST                          0.757283  
BOS_SCI_ENDOTAK_RELIANCE                 0.582519  
STJUDE_DURATA                            0.670240